forum.net/Models/Thread.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace forum.net.Models
{
    public class Thread : BaseEntity
    {
        public int ThreadId { get; set; }

        [Required]
        [StringLength(35)]
        [DisplayName("Tytuł")]
        public string Title { get; set; }

        [DisplayName("Forum")]
        public int ForumId { get; set; }

        [DisplayName("Typ wątku")]
        public int ThreadtypeId { get; set; }

        [ForeignKey("CreatedBy")]
        public string CreatedById { get; set; }

        [ForeignKey("UpdatedBy")]
        public string UpdatedById { get; set; }

        public Threadtype Threadtype { get; set; }
        public Forum Forum { get; set; }
        public ApplicationUser CreatedBy { get; set; }
        public ApplicationUser UpdatedBy { get; set; }

        public virtual ICollection<Post> Posts { get; set; }
    }

    public class ThreadsViewModel
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public Forum Forum { get; set; }
        public ICollection<Thread> Threads { get; set; }
        public ICollection<Post> Posts { get; set; }
        public ICollection<Advert> Adverts => db.Adverts.ToList();
    }

    public class CreateThreadViewModel
    {
        public Thread Thread { get; set; }
        public Forum Forum { get; set; }
        public IEnumerable<SelectListItem> Threadtypes { get; set; }
    }
}

forum.net/Models/Threadtype.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace forum.net.Models
{
    public class Threadtype
    {
        public int ThreadtypeId { get; set; }

        [Required]
        [StringLength(35)]
        [DisplayName("Nazwa")]
        public string Name { get; set; }

        public virtual ICollection<Thread> Threads { get; set; }
    }
}

forum.net/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using forum.net.Models;
using Microsoft.AspNet.Identity;

namespace forum.net.Controllers
{
    
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.CreatedBy).Include(p => p.Thread).Include(p => p.UpdatedBy);
            return View(posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var threads = db.Threads.Where(t => t.ForumId == id).Include(t => t.CreatedBy).ToList();
            var thread = db.Threads.Find(id);
            Post post = new Post();
            post.ThreadId = (int)id;

            return View(new Post { Thread = thread });
        }

        // POST: Posts/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostId,Body,ThreadId,CreatedById,UpdatedById,CreatedAt,UpdatedAt")] Post post, int id)
        {
            if (ModelState.IsValid)
            {

                post.ThreadId = db.Threads.Find(id).ThreadId;
                post.CreatedById = User.Identity.GetUserId();
                post.UpdatedById = User.Identity.GetUserId();
                post.CreatedAt = DateTime.Now;
                post.UpdatedAt = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Details", "Threads", new { id = post.ThreadId });
            }

            ViewBag.CreatedById = new SelectList(db.Users, "Id", "Nickname", post.CreatedById);
            ViewBag.ThreadId = new SelectList(db.Threads, "ThreadId", "Title", post.ThreadId);
            ViewBag.UpdatedById = new SelectList(db.Users, "Id", "Nickname", post.UpdatedById);
            return View(post);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.CreatedById = new SelectList(db.Users, "Id", "Nickname", post.CreatedById);
            ViewBag.ThreadId = new SelectList(db.Threads, "ThreadId", "Title", post.ThreadId);
            ViewBag.UpdatedById = new SelectList(db.Users, "Id", "Nickname", post.UpdatedById);
            return View(post);
        }

        // POST: Posts/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PostId,Body,ThreadId,CreatedById,UpdatedById,CreatedAt,UpdatedAt")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CreatedById = new SelectList(db.Users, "Id", "Nickname", post.CreatedById);
            ViewBag.ThreadId = new SelectList(db.Threads, "ThreadId", "Title", post.ThreadId);
            ViewBag.UpdatedById = new SelectList(db.Users, "Id", "Nickname", post.UpdatedById);
            return View(post);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

forum.net/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using forum.net.Models;
using Microsoft.AspNet.Identity;

namespace forum.net.Controllers
{
    
    public class ThreadsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Threads(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var threads = db.Threads.Where(t => t.ForumId == id).Include(t => t.CreatedBy).OrderByDescending(t => t.ThreadtypeId).ToList();
            var forum = db.Fora.Find(id);
            return View("~/Views/Home/Threads.cshtml", new ThreadsViewModel { Threads = threads, Forum = forum });
        }

        // GET: Threads
        public ActionResult Index()
        {
            var threads = db.Threads.Include(t => t.Threadtype);
            return View(threads.ToList());
        }

        // GET: Threads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var posts = db.Posts.Where(t => t.ThreadId == id).Include(t => t.CreatedBy).ToList();
            Thread thread = db.Threads.Find(id);
            thread.Posts = posts;
            Threadtype threadtype = db.Threadtypes.Find(thread.ThreadtypeId);
            ViewBag.threadname = threadtype.Name;
            ViewBag.ThreadId = thread.ThreadId;
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // GET: Threads/Create
        [Authorize]
        public ActionResult Create(int? forumId)
        {
            if (forumId == null || db.Fora.Find(forumId) == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var forum = db.Fora.Find(forumId);
            var threadtypes = new SelectList(db.Threadtypes, "ThreadtypeId", "Name");
            Thread thread = new Thread();
            thread.ForumId = (int)forumId;
            return View(new CreateThreadViewModel { Forum = forum, Threadtypes = threadtypes, Thread = thread});
        }

        // POST: Threads/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ThreadId,Title,ThreadtypeId,ForumId")] Thread thread, string post_body, int forum_id)
        {
            if (post_body.Length > 255)
                return RedirectToAction("Threads", "Threads", new { id = forum_id });

            if (ModelState.IsValid)
            {
                thread.ForumId = forum_id;
                thread.CreatedById = User.Identity.GetUserId();
                thread.UpdatedById = User.Identity.GetUserId();

                // Tworzenie pierwszego posta w nowym temacie
                Post newPost = new Post();
                newPost.Body = post_body;
                newPost.ThreadId = thread.ThreadId;
                newPost.CreatedById = User.Identity.GetUserId();
                newPost.UpdatedById = User.Identity.GetUserId();

                db.Threads.Add(thread);
                db.Posts.Add(newPost);
                db.SaveChanges();
                return RedirectToAction("Threads", "Threads", new { id = thread.ForumId });
            }

            var forum = db.Fora.Find(thread.ForumId);
            var threadtypes = new SelectList(db.Threadtypes, "ThreadtypeId", "Name");

            return View(new CreateThreadViewModel { Forum = forum, Threadtypes = threadtypes, Thread = thread });
        }

        // GET: Threads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            ViewBag.ThreadtypeId = new SelectList(db.Threadtypes, "ThreadtypeId", "Name", thread.ThreadtypeId);
            return View(thread);
        }

        // POST: Threads/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ThreadId,Title,ThreadtypeId,CreatedById,UpdatedById,CreatedAt,UpdatedAt")] Thread thread)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thread).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ThreadtypeId = new SelectList(db.Threadtypes, "ThreadtypeId", "Name", thread.ThreadtypeId);
            return View(thread);
        }

        // GET: Threads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // POST: Threads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Thread thread = db.Threads.Find(id);
            db.Threads.Remove(thread);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

forum.net/Views/Threads/Create.cshtml
@model forum.net.Models.CreateThreadViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="forum_id" value="@Model.Forum.ForumId">
    
<div class="form-horizontal">
    <h4>Wątek - stwórz</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Thread.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Thread.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Thread.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Thread.ThreadtypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Thread.ThreadtypeId, Model.Threadtypes, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Thread.ThreadtypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group d-none">
        @Html.LabelFor(model => model.Thread.ForumId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Thread.ForumId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Thread.ForumId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="post_body">Treść</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line"
                   data-val="true" data-val-length="Pole Tytuł musi być ciągiem o maksymalnej długości 35."
                   data-val-length-max="35" data-val-required="Pole Tytuł jest wymagane." id="post_body" name="post_body" type="text" value="">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-info">Stwórz</button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index", "Home")
</div>

forum.net/Views/Threads/Delete.cshtml
@model forum.net.Models.Thread

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Thread</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Threadtype.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Threadtype.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedById)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedById)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedById)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

forum.net/Views/Threads/Details.cshtml
@model forum.net.Models.Thread
@{
    ViewBag.Title = "Details";
}

<div>

    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h6 class="mb-0 text-white lh-100">Strona główna -> @Html.DisplayFor(model => model.Title) ->  @ViewBag.threadname </h6>
        </div>
    </div>

    <h3> @Html.DisplayFor(model => model.Title)</h3>

    <br>

    @foreach (var item in Model.Posts)
    {
        <div class="media">
            <img class="align-self-start mr-3" src="https://img.icons8.com/ios/100/000000/guest-male.png" alt="Generic placeholder image" style="width:10%">
            <div class="media-body">

                <h4><b>@item.CreatedBy.Nickname</b></h4>
                @Html.DisplayFor(modelItem => item.Body)
                <hr>Utworzono: @Html.DisplayFor(modelItem => item.CreatedAt)

            </div>
        </div>
        <br>
    }


</div>



<a href='@Url.Action("Create", "Posts", new { id = Model.ThreadId })'>
    <img src='https://cdn0.iconfinder.com/data/icons/social-messaging-ui-color-shapes/128/add-circle-green-512.png' style="width:2%" />
    Dodaj Post
</a>
<br />
<br />

<p>
    @Html.ActionLink("Wróć do listy wątków", "Threads", "Threads", new { id = Model.ForumId }, new { })
</p>

forum.net/Views/Threads/Edit.cshtml
@model forum.net.Models.Thread

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thread</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ThreadId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThreadtypeId, "ThreadtypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ThreadtypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ThreadtypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedById, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedById, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedById, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedById, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedById, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedById, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

forum.net/Views/Threads/Index.cshtml
@model IEnumerable<forum.net.Models.Thread>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Threadtype.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Threadtype.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedById)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedById)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedAt)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ThreadId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ThreadId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ThreadId })
        </td>
    </tr>
}

</table>